// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./../components/src/lib/alert/Alert.vue')['default']
    Cookies: typeof import('./src/app/components/Cookies.vue')['default']
    Logo: typeof import('./src/app/components/widgets/Logo.vue')['default']
    Widget: typeof import('./../components/src/lib/Widget.vue')['default']
  }
}

export { }
