// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/lib/alert/Alert.vue')['default']
    Widget: typeof import('./src/lib/Widget.vue')['default']
  }
}

export { }
